spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      user: user.create.queue
  mail:
    host: email-smtp.us-west-2.amazonaws.com
    port: 587
    username: AKIAQ2UJTAJVPM3VX4MX
    password: BGzpjqFLlKajskSeadSmjrBV7aT92Vpr14vplSLG6Feb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8082
